- name: my play to project 3
  hosts: liki
  become: true
  tasks:
    - name: uupdate repos
      command: apt update
    - name: install docker
      package: name=docker.io state=present
    - name: start docker service
      service: name=docker state=started
    - name: docker con
      command: docker run -d -p 4567:8081 likith2468/insurance:4
